*KO missing FROM
JSON GENERATE x.

*OK
JSON GENERATE x FROM y.
*OK
JSON GENERATE x FROM y COUNT a.
*OK
JSON GENERATE x FROM y COUNT IN a.

*KO missing json name mapping 
JSON GENERATE x FROM y NAME.
*KO incomplete name mapping
JSON GENERATE x FROM y NAME t.

*OK
JSON GENERATE x FROM y NAME data-item 'newName'.

*KO incomplete name mapping
JSON GENERATE x FROM y NAME OF t.

*OK
JSON GENERATE x FROM y NAME OF data-item 'newName'.
*OK
JSON GENERATE x FROM y NAME OF data-item IS 'newName'.
*OK multiple name mappings
JSON GENERATE x FROM y NAME OF o1 IS 'n1' o2 'n2' o3 IS 'n3'.

*KO missing data name to suppress
JSON GENERATE x FROM y SUPPRESS.

*OK
JSON GENERATE x FROM y SUPPRESS t.
*OK multiple suppress directives
JSON GENERATE x FROM y SUPPRESS t1 t2 t3.

*OK
JSON GENERATE x FROM y NAME OF y IS OMITTED.
JSON GENERATE x FROM y NAME OF y OMITTED.
JSON GENERATE x FROM y NAME y IS OMITTED.
JSON GENERATE x FROM y NAME y OMITTED.
*KO OMITTED without NAME
JSON GENERATE x FROM y OMITTED.

*OK
JSON GENERATE x FROM y SUPPRESS WHEN ZERO
JSON GENERATE x FROM y SUPPRESS WHEN ZEROS
JSON GENERATE x FROM y SUPPRESS WHEN ZEROES
JSON GENERATE x FROM y SUPPRESS WHEN SPACE
JSON GENERATE x FROM y SUPPRESS WHEN SPACES
JSON GENERATE x FROM y SUPPRESS WHEN LOW-VALUE
JSON GENERATE x FROM y SUPPRESS WHEN LOW-VALUES
JSON GENERATE x FROM y SUPPRESS WHEN HIGH-VALUE
JSON GENERATE x FROM y SUPPRESS WHEN HIGH-VALUES
JSON GENERATE x FROM y SUPPRESS a WHEN ZERO
JSON GENERATE x FROM y SUPPRESS EVERY NUMERIC WHEN ZERO HIGH-VALUE
JSON GENERATE x FROM y SUPPRESS EVERY NUMERIC WHEN ZERO OR HIGH-VALUE
JSON GENERATE x FROM y SUPPRESS EVERY NUMERIC WHEN ZERO OR HIGH-VALUE HIGH-VALUES
JSON GENERATE x FROM y SUPPRESS EVERY NUMERIC WHEN ZERO OR ZEROS OR ZEROES
JSON GENERATE x FROM y SUPPRESS EVERY NONNUMERIC WHEN SPACE SPACES
JSON GENERATE x FROM y SUPPRESS EVERY NONNUMERIC WHEN SPACE OR SPACES

*KO bad syntax for SUPPRESS with generic-suppression-phrase
JSON GENERATE x FROM y SUPPRESS EVERY WHEN ZERO OR SPACE
JSON GENERATE x FROM y SUPPRESS NUMERIC WHEN ZERO OR HIGH-VALUE

*KO wrong figurative constants in SUPPRESS
JSON GENERATE x FROM y SUPPRESS WHEN QUOTE
JSON GENERATE x FROM y SUPPRESS WHEN QUOTES
JSON GENERATE x FROM y SUPPRESS WHEN NULL
JSON GENERATE x FROM y SUPPRESS WHEN NULLS