*KO missing INTO
JSON PARSE x.

*OK
JSON PARSE x INTO y.
JSON PARSE x INTO y DETAIL.
JSON PARSE x INTO y WITH DETAIL.

*KO
JSON PARSE x INTO y NAME.
JSON PARSE x INTO y NAME a.
JSON PARSE x INTO y NAME OF a.

*OK
JSON PARSE x INTO y NAME data-item 'newName'.
JSON PARSE x INTO y NAME OF data-item 'newName'.
*OK
JSON PARSE x INTO y NAME OF data-item IS 'newName'.
JSON PARSE x INTO y NAME OF data-item IS OMITTED.
*OK multiple name mappings
JSON PARSE x INTO y NAME OF o1 IS 'n1' o2 'n2' o3 IS 'n3'.

*KO missing data name to suppress
JSON PARSE x INTO y SUPPRESS.

*OK
JSON PARSE x INTO y SUPPRESS t.
*OK multiple suppress directives
JSON PARSE x INTO y SUPPRESS t1 t2 t3.

*OK
JSON PARSE x INTO y CONVERTING a BOOL a-flag.
JSON PARSE x INTO y CONVERTING a BOOLEAN USING a1-flag a2-flag.
JSON PARSE x INTO y CONVERTING a FROM JSON BOOL USING a1-flag AND a2-flag.
JSON PARSE x INTO y CONVERTING data-a FROM BOOLEAN USING data-a-flag ALSO data-b FROM BOOLEAN USING data-b-true AND data-b-false ALSO data-c FROM BOOLEAN USING 'a' AND 'z'.

*KO wrong syntax for CONVERTING phrase
JSON PARSE x INTO y CONVERTING.
JSON PARSE x INTO y CONVERTING a.
JSON PARSE x INTO y CONVERTING a b.
JSON PARSE x INTO y CONVERTING a BOOL.
JSON PARSE x INTO y CONVERTING a BOOL USING.
JSON PARSE x INTO y CONVERTING a BOOL USING a1-flag AND.
JSON PARSE x INTO y CONVERTING data-a FROM BOOLEAN USING data-a-flag ALSO.

*OK all together
JSON PARSE x INTO y DETAIL NAME n 'newName' SUPPRESS s1 s2 CONVERTING a FROM JSON BOOL USING a1-flag AND a2-flag.