XML GENERATE x FROM y SUPPRESS WHEN ZERO
XML GENERATE x FROM y SUPPRESS WHEN ZEROS
XML GENERATE x FROM y SUPPRESS WHEN ZEROES
XML GENERATE x FROM y SUPPRESS WHEN SPACE
XML GENERATE x FROM y SUPPRESS WHEN SPACES
XML GENERATE x FROM y SUPPRESS WHEN LOW-VALUE
XML GENERATE x FROM y SUPPRESS WHEN LOW-VALUES
XML GENERATE x FROM y SUPPRESS WHEN HIGH-VALUE
XML GENERATE x FROM y SUPPRESS WHEN HIGH-VALUES
XML GENERATE x FROM y SUPPRESS EVERY NUMERIC ATTRIBUTE WHEN ZERO OR HIGH-VALUE
XML GENERATE x FROM y SUPPRESS EVERY NUMERIC CONTENT   WHEN ZERO OR HIGH-VALUE
XML GENERATE x FROM y SUPPRESS EVERY NUMERIC ELEMENT   WHEN ZERO OR HIGH-VALUE
XML GENERATE x FROM y SUPPRESS EVERY NUMERIC           WHEN ZERO OR HIGH-VALUE
XML GENERATE x FROM y SUPPRESS EVERY NONNUMERIC ATTRIBUTE WHEN SPACE OR SPACES
XML GENERATE x FROM y SUPPRESS EVERY NONNUMERIC CONTENT   WHEN SPACE OR SPACES
XML GENERATE x FROM y SUPPRESS EVERY NONNUMERIC ELEMENT   WHEN SPACE OR SPACES
XML GENERATE x FROM y SUPPRESS EVERY NONNUMERIC           WHEN SPACE OR SPACES
XML GENERATE x FROM y SUPPRESS EVERY ATTRIBUTE              WHEN ZERO OR SPACE
XML GENERATE x FROM y SUPPRESS EVERY CONTENT                WHEN ZERO OR SPACE
XML GENERATE x FROM y SUPPRESS EVERY ELEMENT                WHEN ZERO OR SPACE