
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jul 25 13:35:26 EDT 1999
//----------------------------------------------------

namespace TUVienna.CS_CUP
{

	/** CUP generated class containing symbol constants. */
	public class sym 
	{
		/* terminals */
		public const int NON = 8;
		public const int NONTERMINAL = 27;
		public const int STAR = 15;
		public const int SEMI = 13;
		public const int CODE = 4;
		public const int EOF = 0;
		public const int NONASSOC = 23;
		public const int LEFT = 21;
		public const int PACKAGE = 2;
		public const int COLON = 17;
		public const int WITH = 11;
		public const int IMPORT = 3;
		public const int error = 1;
		public const int COLON_COLON_EQUALS = 18;
		public const int COMMA = 14;
		public const int DOT = 16;
		public const int SCAN = 10;
		public const int ID = 28;
		public const int INIT = 9;
		public const int PARSER = 6;
		public const int TERMINAL = 7;
		public const int PRECEDENCE = 20;
		public const int LBRACK = 25;
		public const int RBRACK = 26;
		public const int PERCENT_PREC = 24;
		public const int START = 12;
		public const int RIGHT = 22;
		public const int BAR = 19;
		public const int ACTION = 5;
		public const int CODE_STRING = 29;
	}
}
