       >>CALLINTERFACE DLL
       >>CALLINTERFACE DYNAMIC
       >>CALLINTERFACE STATIC

       >>CALLINTERFACE DLL BAD
       >>CALLINTERFACE DYNAMIC BAD
       >>CALLINTERFACE STATIC BAD

       >>CALLINT DLL
       >>CALLINT DYNAMIC
       >>CALLINT STATIC

>>CALLINT DLL BAD BEFORE COLUM 8
>>CALLINT DYNAMIC BAD BEFORE COLUM 8
>>CALLINT STATIC BAD BEFORE COLUM 8

