ACCEPT
ACCEPT var1
ACCEPT FROM
ACCEPT FROM SYSIN
ACCEPT var1 FROM
ACCEPT var1 FROM SYSIN
ACCEPT var1 FROM DATE
ACCEPT var1 FROM DATE YYYYMMDD
ACCEPT var1 FROM DAY
ACCEPT var1 FROM DAY YYYYDDD
ACCEPT var1 FROM DAY-OF-WEEK
ACCEPT var1 FROM TIME