ALLOCATE 9 CHARACTERS RETURNING myPointer
ALLOCATE 9 CHARACTERS INITIALIZED RETURNING myPointer
ALLOCATE (2 + 7) * 3 CHARACTERS RETURNING myPointer
ALLOCATE (var1 + var2) CHARACTERS INITIALIZED RETURNING myPointer
ALLOCATE var1
ALLOCATE var1 INITIALIZED
ALLOCATE var1 RETURNING myPointer
ALLOCATE var1 INITIALIZED RETURNING myPointer
* KO required size info missing
ALLOCATE
* KO required size info missing
ALLOCATE INITIALIZED
* KO required CHARACTERS keyword missing
ALLOCATE 12
* KO required CHARACTERS keyword missing
ALLOCATE 12 RETURNING myPointer