CALL f
CALL f RETURNING x
CALL f USING a
CALL f USING a b c
CALL f USING a RETURNING x
CALL f USING a b c RETURNING x
CALL f USING BY REFERENCE a b
CALL f USING BY VALUE     i j
CALL f USING BY CONTENT   m n
CALL f USING BY REFERENCE a b BY VALUE i j BY CONTENT m n
CALL f USING a b BY REFERENCE c d BY REFERENCE e f
CALL f USING BY VALUE i j BY VALUE k l
CALL f USING BY CONTENT m n BY CONTENT o p
CALL f USING a b BY REFERENCE c d BY VALUE i j BY CONTENT m n BY CONTENT o p BY REFERENCE e f BY VALUE k l RETURNING x