*  /////////////////////////////////
* // INSPECT Format 1 (TALLYING)
* CHARACTERS
INSPECT x TALLYING i FOR CHARACTERS
INSPECT x TALLYING i FOR CHARACTERS j FOR CHARACTERS k FOR CHARACTERS
* ALL, LEADING
INSPECT x TALLYING i FOR ALL x
INSPECT x TALLYING i FOR LEADING y
INSPECT x TALLYING i FOR ALL x j FOR LEADING y
* both
INSPECT x TALLYING i FOR CHARACTERS j FOR ALL x k FOR CHARACTERS l FOR LEADING y

*  //////////////////////////////////
* // INSPECT Format 2 (REPLACING)
* CHARACTERS BY
INSPECT x REPLACING CHARACTERS BY i
INSPECT x REPLACING CHARACTERS BY i CHARACTERS BY j CHARACTERS BY k
INSPECT x REPLACING CHARACTERS BY i AFTER a CHARACTERS BY j BEFORE b CHARACTERS BY k AFTER a BEFORE b
* ALL, LEADING, FIRST
INSPECT x REPLACING ALL x BY y

*  ////////////////////////////////////////////////
* // INSPECT Format 3 (TALLYING then REPLACING)
INSPECT x TALLYING i FOR CHARACTERS REPLACING CHARACTERS BY i