START f
START f END-START
START f
  INVALID KEY
    CONTINUE
  NOT INVALID KEY
    CONTINUE
END-START
START f KEY EQUAL a
START f KEY EQUAL a OF b IN c
START f KEY = a
START f KEY GREATER a
START f KEY > a
START f KEY NOT LESS a
START f KEY NOT < a
START f KEY GREATER OR EQUAL a
START f KEY >= a

* ERROR: wrong operator
START f KEY < a
START f KEY LESS a
START f KEY NOT > a
START f KEY NOT GREATER a
START f KEY <= a
START f KEY LESS OR EQUAL a
START f KEY NOT = a
START f KEY NOT EQUAL a