USE GLOBAL AFTER STANDARD EXCEPTION PROCEDURE ON filename.
USE GLOBAL AFTER STANDARD ERROR PROCEDURE ON filename.
USE AFTER STANDARD ERROR PROCEDURE ON filename.
USE AFTER ERROR PROCEDURE ON filename.
USE AFTER ERROR PROCEDURE filename.
USE AFTER ERROR PROCEDURE f1 f2 f3.
USE AFTER ERROR PROCEDURE INPUT.
USE AFTER ERROR PROCEDURE OUTPUT.
USE AFTER ERROR PROCEDURE I-O.
USE AFTER ERROR PROCEDURE EXTEND.
* syntax errors
USE AFTER ERROR PROCEDURE filename INPUT.
USE AFTER ERROR PROCEDURE filename OUTPUT.
USE AFTER ERROR PROCEDURE filename I-O.
USE AFTER ERROR PROCEDURE filename EXTEND.
USE AFTER ERROR PROCEDURE INPUT OUTPUT I-O EXTEND.