//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypeCobol {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TypeCobolResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TypeCobolResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TypeCobol.TypeCobolResource", typeof(TypeCobolResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot REDEFINES aTypedef declaration.
        /// </summary>
        public static string CannotRedefinedTypedefDecl {
            get {
                return ResourceManager.GetString("CannotRedefinedTypedefDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot REDEFINES a Variable whose type is a Strict TYPEDEF..
        /// </summary>
        public static string CannotRedefinesAVariableWhoseTypeDefed {
            get {
                return ResourceManager.GetString("CannotRedefinesAVariableWhoseTypeDefed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Level 66 cannot rename an entry with level {0}..
        /// </summary>
        public static string CannotRenamesLevel {
            get {
                return ResourceManager.GetString("CannotRenamesLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program with identifier &quot;{0}&quot; is defined multiple times..
        /// </summary>
        public static string DuplicateProgram {
            get {
                return ResourceManager.GetString("DuplicateProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;REDEFINES&quot; is not allowed here..
        /// </summary>
        public static string ErrRedefinesNotAllowedHere {
            get {
                return ResourceManager.GetString("ErrRedefinesNotAllowedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;REDEFINES&quot; object &quot;{0}&quot; was not immediatly preceding level-{1} data item..
        /// </summary>
        public static string ErrRedefineWasNotImmediatlyPrec {
            get {
                return ResourceManager.GetString("ErrRedefineWasNotImmediatlyPrec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple REDEFINES Symbol found for : &quot;{0}&quot;.
        /// </summary>
        public static string MultipleRenameSymbolFound {
            get {
                return ResourceManager.GetString("MultipleRenameSymbolFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;RENAMES&quot; object &quot;{0}&quot; contained, or was surbordinated to, an item whose defition contained an &quot;OCCURS&quot; clause..
        /// </summary>
        public static string RenamesContainsOccur {
            get {
                return ResourceManager.GetString("RenamesContainsOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENAMES object &quot;{0}&quot; is not a record..
        /// </summary>
        public static string RenamesNotAGroup {
            get {
                return ResourceManager.GetString("RenamesNotAGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENAMES object &quot;{0}&quot; not found in the immediatly preceding record description..
        /// </summary>
        public static string RenamesObjectNotFound {
            get {
                return ResourceManager.GetString("RenamesObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENAMES object &quot;{0}&quot; started before object &quot;{1}&quot;.
        /// </summary>
        public static string RenamesObjectOrder {
            get {
                return ResourceManager.GetString("RenamesObjectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE&apos;{0}&apos; has already been declared.
        /// </summary>
        public static string TypeAlreadyDeclared {
            get {
                return ResourceManager.GetString("TypeAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve &quot;{0}&quot;.
        /// </summary>
        public static string UnableToResolveVariable {
            get {
                return ResourceManager.GetString("UnableToResolveVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow REDEFINES Symbol : &quot;{0}&quot;.
        /// </summary>
        public static string UnknowRedefinesdSymbol {
            get {
                return ResourceManager.GetString("UnknowRedefinesdSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable {0} was not uniquely defined name..
        /// </summary>
        public static string VariableNotUnique {
            get {
                return ResourceManager.GetString("VariableNotUnique", resourceCulture);
            }
        }
    }
}
