// JavaCup specification for a simple expression evaluator (w/ actions)

namespace TypeCobol.Compiler.CupParser;

using TUVienna.CS_CUP.Runtime;
using System;
using System.Collections;
using System.Collections.Generic;
using TypeCobol.Compiler.CodeElements;

/* Terminals (tokens returned by the scanner). */
terminal TypeCobol.Compiler.CodeElements.ProgramIdentification ProgramIdentification;
terminal TypeCobol.Compiler.CodeElements.ProgramEnd ProgramEnd;
terminal TypeCobol.Compiler.CodeElements.ClassIdentification ClassIdentification;
terminal TypeCobol.Compiler.CodeElements.ClassEnd ClassEnd;
terminal TypeCobol.Compiler.CodeElements.FactoryIdentification FactoryIdentification;
terminal TypeCobol.Compiler.CodeElements.FactoryEnd FactoryEnd;
terminal TypeCobol.Compiler.CodeElements.ObjectIdentification ObjectIdentification;
terminal TypeCobol.Compiler.CodeElements.ObjectEnd ObjectEnd;
terminal TypeCobol.Compiler.CodeElements.MethodIdentification MethodIdentification;
terminal TypeCobol.Compiler.CodeElements.MethodEnd MethodEnd;
terminal TypeCobol.Compiler.CodeElements.EnvironmentDivisionHeader EnvironmentDivisionHeader;
terminal TypeCobol.Compiler.CodeElements.DataDivisionHeader DataDivisionHeader;
terminal TypeCobol.Compiler.CodeElements.ProcedureDivisionHeader ProcedureDivisionHeader;
terminal TypeCobol.Compiler.CodeElements.DeclarativesHeader DeclarativesHeader;
terminal TypeCobol.Compiler.CodeElements.DeclarativesEnd DeclarativesEnd;
terminal TypeCobol.Compiler.CodeElements.SectionHeader SectionHeader;
terminal TypeCobol.Compiler.CodeElements.ConfigurationSectionHeader ConfigurationSectionHeader;
terminal TypeCobol.Compiler.CodeElements.InputOutputSectionHeader InputOutputSectionHeader;
terminal TypeCobol.Compiler.CodeElements.FileSectionHeader FileSectionHeader;
terminal TypeCobol.Compiler.CodeElements.WorkingStorageSectionHeader WorkingStorageSectionHeader;
terminal TypeCobol.Compiler.CodeElements.LocalStorageSectionHeader LocalStorageSectionHeader;
terminal TypeCobol.Compiler.CodeElements.LinkageSectionHeader LinkageSectionHeader;
terminal TypeCobol.Compiler.CodeElements.ParagraphHeader ParagraphHeader;
terminal TypeCobol.Compiler.CodeElements.FileControlParagraphHeader FileControlParagraphHeader;
terminal TypeCobol.Compiler.CodeElements.IOControlParagraphHeader IOControlParagraphHeader;
terminal TypeCobol.Compiler.CodeElements.SentenceEnd SentenceEnd;
terminal TypeCobol.Compiler.CodeElements.FileDescriptionEntry FileDescriptionEntry;
terminal TypeCobol.Compiler.CodeElements.DataDescriptionEntry DataDescriptionEntry;
terminal TypeCobol.Compiler.CodeElements.DataRedefinesEntry DataRedefinesEntry;
terminal TypeCobol.Compiler.CodeElements.DataRenamesEntry DataRenamesEntry;
terminal TypeCobol.Compiler.CodeElements.DataConditionEntry DataConditionEntry;
terminal TypeCobol.Compiler.CodeElements.FileControlEntry FileControlEntry;
terminal TypeCobol.Compiler.CodeElements.IOControlEntry IOControlEntry;
terminal TypeCobol.Compiler.CodeElements.SourceComputerParagraph SourceComputerParagraph;
terminal TypeCobol.Compiler.CodeElements.ObjectComputerParagraph ObjectComputerParagraph;
terminal TypeCobol.Compiler.CodeElements.SpecialNamesParagraph SpecialNamesParagraph;
terminal TypeCobol.Compiler.CodeElements.RepositoryParagraph RepositoryParagraph;
terminal TypeCobol.Compiler.CodeElements.AcceptStatement AcceptStatement;
terminal TypeCobol.Compiler.CodeElements.AddStatement AddStatement;
terminal TypeCobol.Compiler.CodeElements.AllocateStatement AllocateStatement;
terminal TypeCobol.Compiler.CodeElements.AlterStatement AlterStatement;
terminal TypeCobol.Compiler.CodeElements.CallStatement CallStatement;
terminal TypeCobol.Compiler.CodeElements.CancelStatement CancelStatement;
terminal TypeCobol.Compiler.CodeElements.CloseStatement CloseStatement;
terminal TypeCobol.Compiler.CodeElements.ComputeStatement ComputeStatement;
terminal TypeCobol.Compiler.CodeElements.ContinueStatement ContinueStatement;
terminal TypeCobol.Compiler.CodeElements.DeleteStatement DeleteStatement;
terminal TypeCobol.Compiler.CodeElements.DisplayStatement DisplayStatement;
terminal TypeCobol.Compiler.CodeElements.DivideStatement DivideStatement;
terminal TypeCobol.Compiler.CodeElements.EntryStatement EntryStatement;
terminal TypeCobol.Compiler.CodeElements.EvaluateStatement EvaluateStatement;
terminal TypeCobol.Compiler.CodeElements.ExecStatement ExecStatement;
terminal TypeCobol.Compiler.CodeElements.ExecStatementText ExecStatementText;
terminal TypeCobol.Compiler.CodeElements.ExitMethodStatement ExitMethodStatement;
terminal TypeCobol.Compiler.CodeElements.ExitProgramStatement ExitProgramStatement;
terminal TypeCobol.Compiler.CodeElements.ExitStatement ExitStatement;
terminal TypeCobol.Compiler.CodeElements.FreeStatement FreeStatement;
terminal TypeCobol.Compiler.CodeElements.GobackStatement GobackStatement;
terminal TypeCobol.Compiler.CodeElements.GotoStatement GotoStatement;
terminal TypeCobol.Compiler.CodeElements.IfStatement IfStatement;
terminal TypeCobol.Compiler.CodeElements.InitializeStatement InitializeStatement;
terminal TypeCobol.Compiler.CodeElements.InspectStatement InspectStatement;
terminal TypeCobol.Compiler.CodeElements.InvokeStatement InvokeStatement;
terminal TypeCobol.Compiler.CodeElements.JsonGenerateStatement JsonGenerateStatement;
terminal TypeCobol.Compiler.CodeElements.JsonParseStatement JsonParseStatement;
terminal TypeCobol.Compiler.CodeElements.MergeStatement MergeStatement;
terminal TypeCobol.Compiler.CodeElements.MoveStatement MoveStatement;
terminal TypeCobol.Compiler.CodeElements.MultiplyStatement MultiplyStatement;
terminal TypeCobol.Compiler.CodeElements.NextSentenceStatement NextSentenceStatement;
terminal TypeCobol.Compiler.CodeElements.OpenStatement OpenStatement;
terminal TypeCobol.Compiler.CodeElements.PerformProcedureStatement PerformProcedureStatement;
terminal TypeCobol.Compiler.CodeElements.PerformStatement PerformStatement;
terminal TypeCobol.Compiler.CodeElements.ReadStatement ReadStatement;
terminal TypeCobol.Compiler.CodeElements.ReleaseStatement ReleaseStatement;
terminal TypeCobol.Compiler.CodeElements.ReturnStatement ReturnStatement;
terminal TypeCobol.Compiler.CodeElements.RewriteStatement RewriteStatement;
terminal TypeCobol.Compiler.CodeElements.SearchStatement SearchStatement;
terminal TypeCobol.Compiler.CodeElements.SetStatement SetStatement;
terminal TypeCobol.Compiler.CodeElements.SortStatement SortStatement;
terminal TypeCobol.Compiler.CodeElements.StartStatement StartStatement;
terminal TypeCobol.Compiler.CodeElements.StopStatement StopStatement;
terminal TypeCobol.Compiler.CodeElements.StringStatement StringStatement;
terminal TypeCobol.Compiler.CodeElements.SubtractStatement SubtractStatement;
terminal TypeCobol.Compiler.CodeElements.UnstringStatement UnstringStatement;
terminal TypeCobol.Compiler.CodeElements.UseStatement UseStatement;
terminal TypeCobol.Compiler.CodeElements.WriteStatement WriteStatement;
terminal TypeCobol.Compiler.CodeElements.XmlGenerateStatement XmlGenerateStatement;
terminal TypeCobol.Compiler.CodeElements.XmlParseStatement XmlParseStatement;
terminal TypeCobol.Compiler.CodeElements.AtEndCondition AtEndCondition;
terminal TypeCobol.Compiler.CodeElements.NotAtEndCondition NotAtEndCondition;
terminal TypeCobol.Compiler.CodeElements.AtEndOfPageCondition AtEndOfPageCondition;
terminal TypeCobol.Compiler.CodeElements.NotAtEndOfPageCondition NotAtEndOfPageCondition;
terminal TypeCobol.Compiler.CodeElements.OnExceptionCondition OnExceptionCondition;
terminal TypeCobol.Compiler.CodeElements.NotOnExceptionCondition NotOnExceptionCondition;
terminal TypeCobol.Compiler.CodeElements.OnOverflowCondition OnOverflowCondition;
terminal TypeCobol.Compiler.CodeElements.NotOnOverflowCondition NotOnOverflowCondition;
terminal TypeCobol.Compiler.CodeElements.InvalidKeyCondition InvalidKeyCondition;
terminal TypeCobol.Compiler.CodeElements.NotInvalidKeyCondition NotInvalidKeyCondition;
terminal TypeCobol.Compiler.CodeElements.OnSizeErrorCondition OnSizeErrorCondition;
terminal TypeCobol.Compiler.CodeElements.NotOnSizeErrorCondition NotOnSizeErrorCondition;
terminal TypeCobol.Compiler.CodeElements.ElseCondition ElseCondition;
terminal TypeCobol.Compiler.CodeElements.WhenCondition WhenCondition;
terminal TypeCobol.Compiler.CodeElements.WhenOtherCondition WhenOtherCondition;
terminal TypeCobol.Compiler.CodeElements.WhenSearchCondition WhenSearchCondition;
terminal TypeCobol.Compiler.CodeElements.AddStatementEnd AddStatementEnd;
terminal TypeCobol.Compiler.CodeElements.CallStatementEnd CallStatementEnd;
terminal TypeCobol.Compiler.CodeElements.ComputeStatementEnd ComputeStatementEnd;
terminal TypeCobol.Compiler.CodeElements.DeleteStatementEnd DeleteStatementEnd;
terminal TypeCobol.Compiler.CodeElements.DivideStatementEnd DivideStatementEnd;
terminal TypeCobol.Compiler.CodeElements.EvaluateStatementEnd EvaluateStatementEnd;
terminal TypeCobol.Compiler.CodeElements.ExecStatementEnd ExecStatementEnd;
terminal TypeCobol.Compiler.CodeElements.IfStatementEnd IfStatementEnd;
terminal TypeCobol.Compiler.CodeElements.InvokeStatementEnd InvokeStatementEnd;
terminal TypeCobol.Compiler.CodeElements.JsonStatementEnd JsonStatementEnd;
terminal TypeCobol.Compiler.CodeElements.MultiplyStatementEnd MultiplyStatementEnd;
terminal TypeCobol.Compiler.CodeElements.PerformStatementEnd PerformStatementEnd;
terminal TypeCobol.Compiler.CodeElements.ReadStatementEnd ReadStatementEnd;
terminal TypeCobol.Compiler.CodeElements.ReturnStatementEnd ReturnStatementEnd;
terminal TypeCobol.Compiler.CodeElements.RewriteStatementEnd RewriteStatementEnd;
terminal TypeCobol.Compiler.CodeElements.SearchStatementEnd SearchStatementEnd;
terminal TypeCobol.Compiler.CodeElements.StartStatementEnd StartStatementEnd;
terminal TypeCobol.Compiler.CodeElements.StringStatementEnd StringStatementEnd;
terminal TypeCobol.Compiler.CodeElements.SubtractStatementEnd SubtractStatementEnd;
terminal TypeCobol.Compiler.CodeElements.UnstringStatementEnd UnstringStatementEnd;
terminal TypeCobol.Compiler.CodeElements.WriteStatementEnd WriteStatementEnd;
terminal TypeCobol.Compiler.CodeElements.XmlStatementEnd XmlStatementEnd;

// FOR SQL
terminal TypeCobol.Compiler.Sql.CodeElements.Statements.CommitStatement CommitStatement;
terminal TypeCobol.Compiler.Sql.CodeElements.Statements.SelectStatement SelectStatement;


terminal TypeCobol.Compiler.CodeElements.LibraryCopyCodeElement LibraryCopy;
terminal TypeCobol.Compiler.CodeElements.FunctionDeclarationHeader FunctionDeclarationHeader;
terminal TypeCobol.Compiler.CodeElements.FunctionDeclarationEnd FunctionDeclarationEnd;
terminal TypeCobol.Compiler.CodeElements.ProcedureStyleCallStatement ProcedureStyleCall;
terminal TypeCobol.Compiler.CodeElements.GlobalStorageSectionHeader GlobalStorageSectionHeader;
terminal TypeCobol.Compiler.CodeElements.Program Program;

/* Non terminals */
non terminal starts, statementEntry;
non terminal compilationUnit, cobolCompilationUnit;
non terminal cobolProgram, cobolClass, cobolProgramBase, nestedProgram;
non terminal classEndOpt;
non terminal factoryIdentificationOpt;
non terminal factoryIdentification;
non terminal factoryEndOpt;
non terminal factoryDataDivisionOpt;
non terminal factoryDataDivision;
non terminal factoryObjectprocedureDivisionOpt;
non terminal factoryObjectprocedureDivision;
non terminal objectIdentificationOpt;
non terminal objectIdentification;
non terminal objectEndOpt;
non terminal methodDefitionsOpt;
non terminal methodDefitions;
non terminal methodDefition;
non terminal methodEnvironmentDivisionOpt;
non terminal methodEnvironmentDivision;

non terminal programAttributes;
non terminal TypeCobol.Compiler.CodeElements.LibraryCopyCodeElement libraryCopyOpt;
non terminal TypeCobol.Compiler.CodeElements.ProgramEnd programEndOpt;
non terminal nestedProgramOpt;

non terminal TypeCobol.Compiler.CodeElements.EnvironmentDivisionHeader environmentDivisionOpt, environmentDivision;
non terminal configurationSectionOpt, configurationSection;
non terminal inputOutputSectionOpt, inputOutputSection;
non terminal configurationParagraphs;
non terminal configurationParagraph;
non terminal fileControlParagraphOpt, fileControlParagraph;
non terminal fileControlEntriesOpt, fileControlEntries;
non terminal ioControlParagraphOpt, ioControlParagraph, ioControlSentencesOpt;
non terminal ioControlEntries;

non terminal dataDefinitionEntry;
non terminal dataDefinitionEntries, dataDefinitionEntriesOpt;
non terminal execSqlStatement;
non terminal storageEntry;
non terminal storageEntries;
non terminal fileDescriptionEntry;
non terminal fileDescriptionEntriesOpt;
non terminal fileDescriptionEntries;
non terminal fileSection;
non terminal globalStorageSection;
non terminal workingStorageSection;
non terminal localStorageSection;
non terminal linkageSection;
non terminal dataDivisionOpt, dataDivision;

non terminal procedureDivision, procedureDivisionOpt;
non terminal TypeCobol.Compiler.Nodes.Node statement, singleStatement, compoundStatement;
non terminal statements;
non terminal sentence;
non terminal sentences, sentencesOpt;
non terminal paragraph;
non terminal paragraphs;
non terminal section;
non terminal sections, declarativesSections;
non terminal declarativesSection;
non terminal declaratives, declarativesOpt;
non terminal functionDeclaration;
non terminal functionProcedureDivision, functionProcedureDivisionOpt;
non terminal functionOrSectionDeclaration;
non terminal functionOrSectionDeclarations;
non terminal configurationSectionHeader;

non terminal onAtEnd, noAtEnd;
non terminal endConditions;
non terminal onException, noException;
non terminal exceptionConditions;
non terminal onInvalidKey, noInvalidKey;
non terminal keyConditions;
non terminal onOverflow, noOverflow;
non terminal overflowConditions;
non terminal onSizeError, noSizeError;
non terminal sizeErrorConditions;

non terminal addStatementConditional;
non terminal callStatementConditions;
non terminal callStatementConditional;
non terminal computeStatementConditional;
non terminal deleteStatementConditional;
non terminal divideStatementConditional;
non terminal whenConditionClause;
non terminal whenConditionClauses;
non terminal whenSearchConditionClauses;
non terminal whenOtherClause;
non terminal whenSearchConditionClause;
non terminal TypeCobol.Compiler.CodeElements.CodeElement whenEvaluateCondition;
non terminal TypeCobol.Compiler.CupParser.NodeBuilder.CodeElementList whenEvaluateConditions;
non terminal evaluateStatementWithBody;
non terminal ifStatementWithBody;
non terminal elseContinuation;
non terminal invokeStatementConditional;
non terminal jsonGenerateStatementConditional;
non terminal jsonParseStatementConditional;
non terminal multiplyStatementConditional;
non terminal performStatementWithBody;
non terminal readStatementConditional;
non terminal rwStatementCondition;
non terminal rwStatementConditions;
non terminal returnStatementConditional;
non terminal rewriteStatementConditional;
non terminal startStatementConditional;
non terminal stringStatementConditional;
non terminal subtractStatementConditional;
non terminal unstringStatementConditional;
non terminal searchStatementWithBody;
non terminal writeStatementConditional;
non terminal xmlGenerateStatementConditional;
non terminal xmlParseStatementConditional;

non terminal procedureDivisionHeader;
non terminal functionProcedureDivisionHeader;
non terminal sectionHeader;
non terminal paragraphHeader;

non terminal ifstatement;
non terminal elseCondition;
non terminal nextSentenceStatement;
non terminal addStatement;
non terminal callStatement;
non terminal computeStatement;
non terminal deleteStatement;
non terminal divideStatement;
non terminal evaluateStatement;
non terminal invokeStatement;
non terminal jsonGenerateStatement;
non terminal jsonParseStatement;
non terminal multiplyStatement;
non terminal performStatement;
non terminal readStatement;
non terminal returnStatement;
non terminal rewriteStatement;
non terminal searchStatement;
non terminal whenSearchCondition;
non terminal whenEvaluateConditionsStart;
non terminal whenOtherCondition;
non terminal startStatement;
non terminal stringStatement;
non terminal subtractStatement;
non terminal unstringStatement;
non terminal writeStatement;
non terminal xmlGenerateStatement;
non terminal xmlParseStatement;

non terminal atEndCondition;
non terminal notAtEndCondition;
non terminal onExceptionCondition;
non terminal notOnExceptionCondition;
non terminal invalidKeyCondition;
non terminal notInvalidKeyCondition;
non terminal onOverflowCondition;
non terminal notOnOverflowCondition;
non terminal onSizeErrorCondition;
non terminal notOnSizeErrorCondition;

non terminal execStatement;
non terminal execStatementBody;
non terminal sqlStatement;
non terminal execStatementEnd;

start with starts;

starts ::= compilationUnit		/* rule for starting analyzing a compilation unit */
	| StatementEntryPoint statementEntry /* rule for starting analyzing a TypeCobol statement */
	;

compilationUnit ::= {: :} cobolCompilationUnit
	| {: :} /*empty*/
	;

/* The grammar */
cobolCompilationUnit ::= cobolProgram
	{: :}
	|  cobolClass
	{: :}
	|  cobolCompilationUnit cobolProgram
	{: :}
	|  cobolCompilationUnit cobolClass
	{: :}
	;

/*
// --- TypeCobol PROGRAM ---
*/

cobolProgram ::=
	cobolProgramBase
    nestedProgramOpt
	programEndOpt:pe
	{: :}
	;

cobolProgramBase ::=
	programAttributes
	{: :}
	environmentDivisionOpt
	dataDivisionOpt
	procedureDivisionOpt
	{: :}
	;

cobolClass ::= 
	ClassIdentification
	EnvironmentDivisionHeader
	factoryIdentificationOpt
	objectIdentificationOpt
	classEndOpt
	{: :}
	;

classEndOpt ::= /*Empty*/
		{: :}
	|	ClassEnd
		{: :}
		;

factoryIdentificationOpt ::= /*empty*/
		{: :}
	| factoryIdentification
		{: :}
	;

factoryIdentification ::= FactoryIdentification factoryDataDivisionOpt factoryObjectprocedureDivisionOpt factoryEndOpt
		{: :}
	;

factoryEndOpt ::= /*empty*/
	{: :}
	| FactoryEnd
	{: :}
	;
		
factoryDataDivisionOpt ::= /*empty*/
		{: :}
	|	factoryDataDivision
		{: :}
	;	

factoryDataDivision ::= DataDivisionHeader workingStorageSection factoryObjectprocedureDivisionOpt
		{: :}
	;	

factoryObjectprocedureDivisionOpt ::= /*empty*/
		{: :}
	|	factoryObjectprocedureDivision
		{: :}
	;	

factoryObjectprocedureDivision ::= ProcedureDivisionHeader methodDefitionsOpt
		{: :}
	;	

objectIdentificationOpt ::= /*empty*/
		{: :}
	|	objectIdentification
		{: :}
	;	

objectIdentification ::= ObjectIdentification workingStorageSection factoryObjectprocedureDivisionOpt objectEndOpt
		{: :}
	;	

objectEndOpt ::= /* empty */
		{: :}
	| ObjectEnd
		{: :}
	;

methodDefitionsOpt ::= /* empty */
		{: :}
	|	methodDefitions
		{: :}
	;	

methodDefitions ::= methodDefition
		{: :}
	| methodDefitions methodDefition
		{: :}
	;

methodDefition ::= MethodIdentification methodEnvironmentDivisionOpt dataDivisionOpt procedureDivisionOpt MethodEnd
	{: :}
	;

methodEnvironmentDivisionOpt ::= /*empty*/
	{: :}
	| methodEnvironmentDivision
	{: :}
	;

methodEnvironmentDivision ::=
	EnvironmentDivisionHeader
	inputOutputSectionOpt
	{: :}
	;

// TCRFUN_LIBRARY_COPY
programAttributes ::= ProgramIdentification:pid libraryCopyOpt:lc
	{: :}
	;

libraryCopyOpt ::= /*empty */
	{: :}
	| LibraryCopy:lc
	{: :}
	;

programEndOpt ::= /* empty */
	| ProgramEnd:pe
	{: :}
	;

nestedProgram ::= 	
	cobolProgramBase
    nestedProgramOpt
	ProgramEnd:pe
	{: :}
	;

nestedProgramOpt ::= /* Empty */
	{: :}
	| nestedProgramOpt nestedProgram
	{: :}
	;

/*
// --- ENVIRONMENT DIVISION ---
*/

environmentDivisionOpt ::= /*empty*/
	{: :}
	| environmentDivision
	{: :}
	;

environmentDivision ::=
	EnvironmentDivisionHeader:edh  
	{: :}
	configurationSectionOpt
	inputOutputSectionOpt
	{: :}
	;

configurationSectionOpt ::= /*empty*/
	{: :}
	| configurationSection
	{: :}
	;

configurationSection ::= configurationSectionHeader 
	{: :}
	| configurationSectionHeader
	  configurationParagraphs
	{: :}
	;

configurationSectionHeader ::= ConfigurationSectionHeader:csh
	{: :}
	;

configurationParagraphs ::= configurationParagraph
		{: :}
	| configurationParagraphs configurationParagraph
		{: :}
	;

configurationParagraph ::= 
      SourceComputerParagraph:scp
	{: :}
	| ObjectComputerParagraph:ocp
	{: :}
	| SpecialNamesParagraph:snp
	{: :}
	| RepositoryParagraph:rp
	{: :}
	;

inputOutputSectionOpt ::= /*empty*/
	{: :}
	| inputOutputSection
	{: :}
	;

inputOutputSection ::= 
	InputOutputSectionHeader:iosh
	{: :}
	fileControlParagraphOpt
	ioControlParagraphOpt
	{: :}
	;

fileControlParagraphOpt ::= /*empty*/
	{: :}
	| fileControlParagraph
	{: :}
	;

fileControlParagraph ::=
	FileControlParagraphHeader:fcph
	{: :}
	fileControlEntriesOpt
	{: :}
	;

fileControlEntriesOpt ::= /*empty*/
		{: :}
	| fileControlEntries
		{: :}
	;

fileControlEntries ::= FileControlEntry:fce
		{: :}
	| fileControlEntries:fces FileControlEntry:fce
		{: :}
	;

ioControlParagraphOpt ::= /*empty*/
		{: :}
	| ioControlParagraph
		{: :}
	;

ioControlParagraph ::= 
	IOControlParagraphHeader
	ioControlSentencesOpt
	{: :}
	;

ioControlSentencesOpt ::= /* empty */	
		{: :}
	| ioControlEntries SentenceEnd
		{:	:}
	;

ioControlEntries ::= IOControlEntry
		{: :}
	| ioControlEntries IOControlEntry
		{: :}
	;


/*
// --- DATA DIVISION ---
*/
dataDivisionOpt ::= /*empty*/
	{: :}
	| dataDivision
	{: :}
	;

dataDivision ::=
	DataDivisionHeader:ddh
	{: :}
	fileSection
	globalStorageSection
	workingStorageSection
	localStorageSection
	linkageSection
	{: :}
//|	error FileSectionHeader
//| error GlobalStorageSection
//|	error WorkingStorageSectionHeader
//|	error LocalStorageSectionHeader
//|	error LinkageSectionHeader
	;

fileSection ::= /*empty*/
	{: :}
	| FileSectionHeader:feh 
	{: :}
	fileDescriptionEntriesOpt
	{: :}
	| error fileDescriptionEntries
	{: :}
	;

fileDescriptionEntriesOpt ::= /*empty*/
	{: :}
	| fileDescriptionEntries
	{: :}
	;

fileDescriptionEntries ::=
	fileDescriptionEntry
	{: :}
	| fileDescriptionEntries fileDescriptionEntry
	{: :}
	;

fileDescriptionEntry ::= 
	FileDescriptionEntry:fde 
	{: :}
	dataDefinitionEntries
	{: :}
	;

workingStorageSection ::= /*empty*/
	{: :}
	| WorkingStorageSectionHeader:wssh 
	{: :}
	  storageEntries
	{: :}
	;

	globalStorageSection ::= /*empty*/
	{: :}
	| GlobalStorageSectionHeader:gssh 
	{: :}
	  storageEntries
	{: :}
	;

storageEntries ::= /*empty*/
	{: :}
	| storageEntries storageEntry
	{: :}
	;

storageEntry ::= dataDefinitionEntry
	{: :}
	| execSqlStatement
	{: :}
	;

execStatement ::= ExecStatement:stmt
	{: :}
	execStatementBody
	execStatementEnd	
;

execStatementBody ::= /* empty */
|	ExecStatementText:text
{: :}
|	execStatementBody ExecStatementText:text
{: :}
|	sqlStatement
{: :}
|	execStatementBody sqlStatement
{: :}
;

sqlStatement ::= CommitStatement:stmt
{: :}
|	SelectStatement:stmt
{: :}
;

execStatementEnd ::= ExecStatementEnd:stmt
{: :}
;

execSqlStatement ::= execStatement:stmt
	{: :}
	| execStatement SentenceEnd
	{: /*Have End*/ :}
	;

localStorageSection ::= /*empty*/
	{: :}
	| LocalStorageSectionHeader:lsh 
	{: :}
	storageEntries
	{: :}
	;

dataDefinitionEntriesOpt ::= /*empty*/
	{: :}
	| dataDefinitionEntries
	{: :}
	;

dataDefinitionEntries ::= dataDefinitionEntry
	{: :}
	| dataDefinitionEntries dataDefinitionEntry
	{: :}
	;

dataDefinitionEntry ::=
	  DataDescriptionEntry:dde
	{: :}
	| DataRedefinesEntry:dre
	{: :}
	| DataRenamesEntry:dre
	{: :}
	| DataConditionEntry:dce
	{: :}
	;

linkageSection ::= /*empty*/
	{: :}
	| LinkageSectionHeader:lsh 
	{: :}
	dataDefinitionEntriesOpt
	{: :}
	;

procedureDivisionOpt ::= /*empty*/
	{: :}
	| procedureDivision
	{: :}
	;

// TCRFUN_DECLARATION_AS_NESTED_PROGRAM
procedureDivision ::=
	procedureDivisionHeader
	declarativesOpt
	functionOrSectionDeclarations
	{: :}
	;

procedureDivisionHeader ::= ProcedureDivisionHeader:pdh 
	{: :}
	;

functionOrSectionDeclarations ::= /*empty*/
	{: :}
	| functionOrSectionDeclarations functionOrSectionDeclaration
	{: :}
	;

functionOrSectionDeclaration ::= functionDeclaration
	{: :}
	| section
	{: :}
	;

// - custom header
// TCRFUN_DECLARATION_NO_IDENTIFICATION_DIVISION
// TCRFUN_DECLARATION_NO_ENVIRONMENT_DIVISION
// TCRFUN_MANDATORY_END_DECLARE
functionDeclaration ::=
	FunctionDeclarationHeader:fdh
	{: :}
	dataDivisionOpt
	functionProcedureDivisionOpt
	FunctionDeclarationEnd:fe
	{: :}
	;

functionProcedureDivisionOpt ::= /*empty*/
	{: :}
	| functionProcedureDivision
	{: :}
	;

functionProcedureDivision ::=
	functionProcedureDivisionHeader 
	{: :}
| 	functionProcedureDivisionHeader
	sections
	{: :}
	;

functionProcedureDivisionHeader ::= ProcedureDivisionHeader:pdh 
	{: :}
	declarativesOpt
	;

declarativesOpt ::= /*empty*/
	{: :}
	| declaratives
	{: :}
	;

declaratives ::=
	DeclarativesHeader:dh
	{: :}
	declarativesSections
	DeclarativesEnd:de
	{: :}
	;


declarativesSections ::= declarativesSection
	{: :}
	| declarativesSections declarativesSection
	{: :}
	;

declarativesSection ::= 
	sectionHeader
	UseStatement :us
	{: :}
	| sectionHeader
	UseStatement :us
	{: :} 
	paragraphs
	{: :}
	;

sections ::= section
	{: :}
	| sections section
	{: :}
	;

section ::= sectionHeader 
	{: :}
	| sectionHeader paragraphs
	{: :}
	| paragraphs
	{: :}
	| sentences
	{: :}
	;

sectionHeader ::= SectionHeader:sh 
	{: :}
	;

paragraphHeader ::= ParagraphHeader:ph 
	{: :}
	;

paragraphs ::= paragraph
	{: :}
	| paragraphs paragraph
	{: :}
	;

paragraph ::= 
	paragraphHeader	
	{: :}
	| paragraphHeader sentences
	{: :}
	| sentences
	{: :}
	;

sentences ::= sentence
	{: :}
	| sentences sentence
	;

sentence ::= SentenceEnd:send
	  {: :}
    | statements SentenceEnd:send
	  {: :}
	| execStatement:stmt
	{: :}
	| error SentenceEnd:send
	{: :}
	| error statements SentenceEnd:send
	{: :}
	;

statementEntry ::= statement
	| StatementEntryPoint ifstatement
	{: :}
	| StatementEntryPoint searchStatement
	{: :}
	;

statements ::= statement
	{: :}
	| statements statement
	{: :}
	;

statement ::= singleStatement
	{: :}
	| compoundStatement
	{: :}
	;

singleStatement ::=
	ContinueStatement:stmt
	{: :}
	| EntryStatement:stmt
	{: :}
// -- arithmetic --
// -- see computeStatementConditional --
// -- data movement --
	| AcceptStatement:stmt // (DATE, DAY, DAY-OF-WEEK, TIME)
	{: :}
	| InitializeStatement:stmt
	{: :}
	| InspectStatement:stmt
	{: :}
	| MoveStatement:stmt
	{: :}
	| SetStatement:stmt
	{: :}
// -- ending --
	| StopStatement:stmt
	{: :}
	| ExitMethodStatement:stmt
	{: :}
	| ExitProgramStatement:stmt
	{: :}
	| GobackStatement:stmt
	{: :}
// -- input-output --
	| CloseStatement:stmt
	{: :}
	| DisplayStatement:stmt
	{: :}
	| OpenStatement:stmt
	{: :}
// -- ordering --
	| MergeStatement:stmt
	{: :}
	| ReleaseStatement:stmt
	{: :}
	| SortStatement:stmt
	{: :}
// -- procedure-branching --
	| AlterStatement:stmt
	{: :}
	| ExitStatement:stmt
	{: :}
	| GotoStatement:stmt
	{: :}
	| PerformProcedureStatement:stmt
	{: :}
// -- program or method linkage --// TYPECOBOL
	| ProcedureStyleCall:stmt
	{: :}
	| ProcedureStyleCall:stmt CallStatementEnd:end
	{: :}
	| CancelStatement:stmt
	{: :}
// -- DB2 & CICS integration --
	| execStatement:stmt
	{: :}
// -- dynamic allocation --
	| AllocateStatement:stmt
	{: :}
	| FreeStatement:stmt
	{: :}
	;
	
// Statements with optional body  
compoundStatement ::= addStatementConditional
		{: :}
	|	callStatementConditional
		{: :}
	|	computeStatementConditional
		{: :}
	|	deleteStatementConditional
		{: :}
	|	evaluateStatementWithBody
		{: :}
	|	ifStatementWithBody
		{: :}
	|	invokeStatementConditional
		{: :}
	|	jsonGenerateStatementConditional
		{: :}
	|	jsonParseStatementConditional
		{: :}
	|	divideStatementConditional
		{: :}
	|	multiplyStatementConditional
		{: :}
	|	performStatementWithBody
		{: :}
	|	readStatementConditional
		{: :}
	|	returnStatementConditional
		{: :}
	|	rewriteStatementConditional
		{: :}
	|	searchStatementWithBody
		{: :}
	|	startStatementConditional
		{: :}
	|	stringStatementConditional
		{: :}
	|	subtractStatementConditional
		{: :}
	|	unstringStatementConditional
		{: :}
	|	writeStatementConditional
		{: :}
	|	xmlGenerateStatementConditional
		{: :}
	|	xmlParseStatementConditional
		{: :}
	;

addStatementConditional ::=
		addStatement
		{: :}
	|	addStatement AddStatementEnd:end
		{: :}
	|	addStatement sizeErrorConditions
		{: :}
	|	addStatement sizeErrorConditions AddStatementEnd:end
		{: :}
	;

addStatement ::= AddStatement:stmt
	{: :}
	;

callStatementConditional ::=
		callStatement
		{: :}
	|	callStatement CallStatementEnd:end
		{: :}
	|	callStatement callStatementConditions
		{: :}
	|	callStatement callStatementConditions CallStatementEnd:end
		{: :}
	;

callStatement ::= CallStatement:stmt
	{: :}
	;

callStatementConditions ::=
	  onException
	{: :}
	| noException
	{: :}
	| onOverflow
	{: :}
	;

computeStatementConditional ::=
		computeStatement
		{: :}
	|	computeStatement ComputeStatementEnd:end
		{: :}
	|	computeStatement sizeErrorConditions
		{: :}
	|	computeStatement sizeErrorConditions ComputeStatementEnd:end
		{: :}
	;

computeStatement ::= ComputeStatement:stmt
	{: :}
	;

deleteStatementConditional ::=
		deleteStatement
		{: :}
	|	deleteStatement DeleteStatementEnd:end
		{: :}
	|	deleteStatement keyConditions
		{: :}
	|	deleteStatement keyConditions DeleteStatementEnd:end
		{: :}
	;

deleteStatement ::= DeleteStatement:stmt
	{: :}
	;


divideStatementConditional ::=
		divideStatement
		{: :}
	|	divideStatement DivideStatementEnd:end
		{: :}
	|	divideStatement sizeErrorConditions
		{: :}
	|	divideStatement sizeErrorConditions DivideStatementEnd:end
		{: :}
	;

divideStatement ::= DivideStatement:stmt
	{: :}
	;

evaluateStatementWithBody ::=
		evaluateStatement
		{: :}
	|	evaluateStatement EvaluateStatementEnd:ese
		{: :}
	|	evaluateStatement whenConditionClauses
		{: :}
	|	evaluateStatement whenConditionClauses  EvaluateStatementEnd:ese
		{: :}
	|	evaluateStatement whenOtherClause
		{: :}
	|	evaluateStatement whenOtherClause EvaluateStatementEnd:ese
		{: :}
	|	evaluateStatement whenConditionClauses whenOtherClause
		{: :}
	|	evaluateStatement whenConditionClauses whenOtherClause EvaluateStatementEnd:ese
		{: :}

	|	evaluateStatement whenConditionClauses error EvaluateStatementEnd:ese
		{: :}
	|	evaluateStatement whenConditionClauses error whenOtherClause
		{: :}
	|	evaluateStatement whenConditionClauses error whenOtherClause EvaluateStatementEnd:ese
		{: :}
	;

evaluateStatement ::= EvaluateStatement:est
	{: :}
	;

whenConditionClauses ::= 
		whenConditionClause
		{: :}
	|	whenConditionClauses whenConditionClause
		{: :}
	|	error whenConditionClause
	|	whenConditionClauses error whenConditionClause
	;

whenConditionClause ::=  whenEvaluateConditionsStart
    {: :}
	| whenEvaluateConditionsStart  statements
	{: :}
	;

whenEvaluateCondition ::= WhenSearchCondition:wec
	{: :}
	| WhenCondition:wec
	{: :}
	;

whenEvaluateConditions ::= whenEvaluateCondition:wec
	{: :}
	| whenEvaluateConditions:wecs whenEvaluateCondition:wec
	{: :}
	;

whenEvaluateConditionsStart ::= whenEvaluateConditions:wecs
	{: :}
	;


whenOtherClause ::= whenOtherCondition:woc statements
	{: :}
	;

whenOtherCondition ::= WhenOtherCondition:woc 
	{: :}
	;

ifStatementWithBody ::=
	ifstatement
    {: :}
    | ifstatement elseContinuation
    | ifstatement IfStatementEnd:end
    {: :}
	
    | ifstatement statements
    {: :}
    | ifstatement statements elseContinuation
    | ifstatement statements IfStatementEnd:end
    {: :}
    
	| ifstatement nextSentenceStatement
    {: :}
    | ifstatement nextSentenceStatement elseContinuation
    | ifstatement nextSentenceStatement IfStatementEnd:end
    {: :}
	;

elseContinuation ::=
    elseCondition
    {: :}
    | elseCondition IfStatementEnd:end
    {: :}
    | elseCondition statements
    {: :}
    | elseCondition statements IfStatementEnd:end
    {: :}
    | elseCondition nextSentenceStatement
    {: :}
    | elseCondition nextSentenceStatement IfStatementEnd:end
    {: :}
    ;

ifstatement ::= IfStatement:ifs
	{: :}
	;

elseCondition ::= ElseCondition:ec 
	{: :}
	;

nextSentenceStatement ::= NextSentenceStatement:next
	{: :}
	;

invokeStatementConditional ::=
		invokeStatement
		{: :}
	|	invokeStatement InvokeStatementEnd:end
		{: :}
	|	invokeStatement exceptionConditions
		{: :}
	|	invokeStatement exceptionConditions InvokeStatementEnd:end
		{: :}
	;

invokeStatement ::= InvokeStatement:stmt
	{: :}
	;

jsonGenerateStatementConditional ::=
		jsonGenerateStatement
		{: :}
	|	jsonGenerateStatement JsonStatementEnd:end
		{: :}
	|	jsonGenerateStatement exceptionConditions
		{: :}
	|	jsonGenerateStatement exceptionConditions JsonStatementEnd:end
		{: :}
	;

jsonGenerateStatement ::= JsonGenerateStatement:stmt
	{: :}
	;

jsonParseStatementConditional ::=
		jsonParseStatement
		{: :}
	|	jsonParseStatement JsonStatementEnd:end
		{: :}
	|	jsonParseStatement exceptionConditions
		{: :}
	|	jsonParseStatement exceptionConditions JsonStatementEnd:end
		{: :}
	;

jsonParseStatement ::= JsonParseStatement:stmt
	{: :}
	;

multiplyStatementConditional ::=
		multiplyStatement
		{: :}
	|	multiplyStatement MultiplyStatementEnd:end
		{: :}
	|	multiplyStatement sizeErrorConditions
		{: :}
	|	multiplyStatement sizeErrorConditions MultiplyStatementEnd:end
		{: :}
	;

multiplyStatement ::= MultiplyStatement:stmt
	{: :}
	;

performStatementWithBody ::=			
		performStatement
		{: :}
	|	performStatement PerformStatementEnd:end
		{: :}
	|	performStatement statements
		{: :}
	|	performStatement statements PerformStatementEnd:end
		{: :}
	;

performStatement ::= PerformStatement:stmt
	{: :}
	;

readStatementConditional ::=
		readStatement
		{: :}
	|	readStatement ReadStatementEnd:end
		{: :}
	|	readStatement rwStatementConditions
		{: :}
	|	readStatement rwStatementConditions ReadStatementEnd:end
		{: :}
	;

readStatement ::= ReadStatement:stmt
	{: :}
	;

rwStatementCondition ::=
	  onAtEnd
	{: :}
	| noAtEnd
	{: :}
	| onInvalidKey
	{: :}
	| noInvalidKey
	{: :}
	;

rwStatementConditions ::=
		rwStatementCondition
		{: :}
	|	rwStatementConditions rwStatementCondition
		{: :}
	;

returnStatementConditional ::=
		returnStatement
		{: :}
	|	returnStatement ReturnStatementEnd:end
		{: :}
	|	returnStatement endConditions
		{: :}
	|	returnStatement endConditions ReturnStatementEnd:end
		{: :}
	;

returnStatement ::= ReturnStatement:stmt
	{: :}
	;

rewriteStatementConditional ::=
		rewriteStatement
		{: :}
	|	rewriteStatement RewriteStatementEnd:end
		{: :}
	|	rewriteStatement keyConditions
		{: :}
	|	rewriteStatement keyConditions RewriteStatementEnd:end
		{: :}
	;

rewriteStatement ::= RewriteStatement:stmt
	{: :}
	;

searchStatementWithBody ::=
		searchStatement SearchStatementEnd:end
		{: :}
	|	searchStatement whenSearchConditionClauses
		{: :}
	|	searchStatement whenSearchConditionClauses SearchStatementEnd:end
		{: :}
	|	searchStatement onAtEnd whenSearchConditionClauses:wsccs
		{: :}
	|	searchStatement onAtEnd whenSearchConditionClauses SearchStatementEnd:end
		{: :}
	;

searchStatement ::= SearchStatement:stmt
	{: :}
	;

whenSearchConditionClause ::=
		whenSearchCondition 
		{: :}
	|	onAtEnd
		{: :}
	|	whenSearchCondition  statements
		{: :}
	|	whenSearchCondition  nextSentenceStatement
		{: :}
	;

whenSearchCondition ::= WhenSearchCondition:wsc
	{: :}
	;

whenSearchConditionClauses ::= whenSearchConditionClause
		{: :}
	|	whenSearchConditionClauses whenSearchConditionClause
		{: :}
	;

startStatementConditional ::=
		startStatement
		{: :}
	|	startStatement StartStatementEnd:end
		{: :}
	|	startStatement keyConditions
		{: :}
	|	startStatement keyConditions StartStatementEnd:end
		{: :}
	;

startStatement ::= StartStatement:stmt
	{: :}
	;

stringStatementConditional ::=
		stringStatement
		{: :}
	|	stringStatement StringStatementEnd:end
		{: :}
	|	stringStatement overflowConditions
		{: :}
	|	stringStatement overflowConditions StringStatementEnd:end
		{: :}
	;

stringStatement ::= StringStatement:stmt
	 {: :}
	 ;

subtractStatementConditional ::=
		subtractStatement
		{: :}
	|	subtractStatement SubtractStatementEnd:end
		{: :}
	|	subtractStatement sizeErrorConditions
		{: :}
	|	subtractStatement sizeErrorConditions SubtractStatementEnd:end
		{: :}
	;

subtractStatement ::= SubtractStatement:stmt
	{: :}
	;

unstringStatementConditional ::=
		unstringStatement
		{: :}
	|	unstringStatement UnstringStatementEnd:end
		{: :}
	|	unstringStatement overflowConditions
		{: :}
	|	unstringStatement overflowConditions UnstringStatementEnd:end
		{: :}
	;

unstringStatement ::= UnstringStatement:stmt
	{: :}
	;

writeStatementConditional ::=
		writeStatement
		{: :}
	|	writeStatement WriteStatementEnd:end
		{: :}
	|	writeStatement rwStatementConditions
		{: :}
	|	writeStatement rwStatementConditions WriteStatementEnd:end
		{: :}
	;

writeStatement ::= WriteStatement:stmt
	{: :}
	;

xmlGenerateStatementConditional ::=
		xmlGenerateStatement
		{: :}
	|	xmlGenerateStatement XmlStatementEnd:end
		{: :}
	|	xmlGenerateStatement exceptionConditions
		{: :}
	|	xmlGenerateStatement exceptionConditions XmlStatementEnd:end
		{: :}
	;

xmlGenerateStatement ::= XmlGenerateStatement:stmt
	{: :}
	;

xmlParseStatementConditional ::=
		xmlParseStatement
		{: :}
	|	xmlParseStatement XmlStatementEnd:end
		{: :}
	|	xmlParseStatement exceptionConditions
		{: :}
	|	xmlParseStatement exceptionConditions XmlStatementEnd:end
		{: :}
	;

xmlParseStatement ::= XmlParseStatement:stmt
	{: :}
	;

// Conditional execution of statements

onAtEnd ::= atEndCondition statements
	{: :}
	;

atEndCondition ::= AtEndCondition:cond 
	{: :}
	;

noAtEnd ::= notAtEndCondition statements
	{: :}
	;

notAtEndCondition ::= NotAtEndCondition:cond 
	{: :}
	;

endConditions ::= onAtEnd
	{: :}
	| noAtEnd
	{: :}
	| endConditions onAtEnd
	{: :}
	| endConditions noAtEnd
	{: :}
	;

onException ::= onExceptionCondition statements
	{: :}
	;

onExceptionCondition ::= OnExceptionCondition:cond 
	{: :}
	;

noException ::= notOnExceptionCondition statements
	{: :}
	;

notOnExceptionCondition ::= NotOnExceptionCondition:cond 
	{: :}
	;

exceptionConditions ::= onException
	{: :}
	| noException
	{: :}
	| exceptionConditions onException
	{: :}
	| exceptionConditions noException
	{: :}
	;


onInvalidKey ::= invalidKeyCondition statements
	{: :}
	;

invalidKeyCondition ::= InvalidKeyCondition:cond 
	{: :}
	;

noInvalidKey ::= notInvalidKeyCondition statements
	{: :}
	;

notInvalidKeyCondition ::= NotInvalidKeyCondition:cond 
	{: :}
	;

keyConditions ::= onInvalidKey
	{: :}
	| noInvalidKey
	{: :}
	| keyConditions onInvalidKey
	{: :}
	| keyConditions noInvalidKey
	{: :}
	;

onOverflow ::= onOverflowCondition statements
	{: :}
	;
onOverflowCondition ::= OnOverflowCondition:cond 
	{: :}
	;

noOverflow ::= notOnOverflowCondition statements
	{: :}
	;

notOnOverflowCondition ::= NotOnOverflowCondition:cond 
	{: :}
	;

overflowConditions ::= onOverflow
	{: :}
	| noOverflow
	{: :}
	| overflowConditions onOverflow
	{: :}
	| overflowConditions noOverflow
	{: :}
	;

onSizeError ::= onSizeErrorCondition statements
	{: :}
	;
onSizeErrorCondition ::= OnSizeErrorCondition:cond 
	{: :}
	;

noSizeError ::= notOnSizeErrorCondition statements
	{: :}
	;

notOnSizeErrorCondition ::= NotOnSizeErrorCondition:cond 
	{: :}
	;

sizeErrorConditions ::= 
	  onSizeError
		{: :}
	| noSizeError
		{: :}
	| sizeErrorConditions onSizeError
		{: :}
	| sizeErrorConditions noSizeError
		{: :}
	;
