using System.Linq;

namespace TypeCobol.Compiler.Scanner
{
    // WARNING : both enumerations below (families / types) must stay in sync
    // WARNING : make sure to update the tables in TokenUtils if you add one more token family or one more token type

    public enum TokenFamily
    {
        //          0 : Error
        Invalid=0,
        //   1 ->   3 : Whitespace
        // p46: The separator comma and separator semicolon can
        // be used anywhere the separator space is used.
        Whitespace=1,
        //   4 ->   5 : Comments
        Comments=4,
        // 6 ->  11 : Separators - Syntax
        SyntaxSeparator=6,
        //  12 ->  16 : Special character word - Arithmetic operators
        ArithmeticOperator=12,
        //  17 ->  21 : Special character word - Relational operators
        RelationalOperator=17,
        //  22 ->  27 : Literals - Alphanumeric
        AlphanumericLiteral=22,
        //  28 ->  31 : Literals - Numeric 
        NumericLiteral=28,
        //  32 ->  34 : Literals - Syntax tokens
        SyntaxLiteral=32,
        //  35 ->  39 : Symbols
        Symbol=35,
        //  40 ->  58 : Keywords - Compiler directive starting tokens
        CompilerDirectiveStartingKeyword=40,
        //  59 ->  153 : Keywords - Code element starting tokens
        CodeElementStartingKeyword=59,
        // 154 -> 184 : Keywords - Special registers
        SpecialRegisterKeyword=154,
        // 185 -> 198 : Keywords - Figurative constants
        FigurativeConstantKeyword=185, 
        // 199 -> 200 : Keywords - Special object identifiers
        SpecialObjetIdentifierKeyword=199,
        // 201 -> 450 : Keywords - Syntax tokens
        SyntaxKeyword=201,
        // 451 -> 452 : Keywords - Cobol 2002
        Cobol2002Keyword = 451,
        // 453 -> 457 : Keywords - TypeCobol
        TypeCobolKeyword = 453,

        // 458 -> 458 : Operators - TypeCobol
        TypeCobolOperators= 458, 

        // 459 -> 461 : Compiler directives
        CompilerDirective = 459,
        // 464 -> 464 : Internal token groups - used by the preprocessor only
        InternalTokenGroup = 460
    }

    // INFO : the list below is generated from the file Documentation/Studies/CobolLexer.tokens.xls
    // WARNING : the list of tokens in CobolWords.g4 must stay in sync

    public enum TokenType
    {
        EndOfFile = -1,
        InvalidToken = 0,
        SpaceSeparator = 1,
        CommaSeparator = 2,
        SemicolonSeparator = 3,
        FloatingComment = 4,
        CommentLine = 5,
        PeriodSeparator = 6,
        ColonSeparator = 7,
        QualifiedNameSeparator = 8,
        LeftParenthesisSeparator = 9,
        RightParenthesisSeparator = 10,
        PseudoTextDelimiter = 11,
        PlusOperator = 12,
        MinusOperator = 13,
        DivideOperator = 14,
        MultiplyOperator = 15,
        PowerOperator = 16,
        LessThanOperator = 17,
        GreaterThanOperator = 18,
        LessThanOrEqualOperator = 19,
        GreaterThanOrEqualOperator = 20,
        EqualOperator = 21,
        AlphanumericLiteral = 22,
        HexadecimalAlphanumericLiteral = 23,
        NullTerminatedAlphanumericLiteral = 24,
        NationalLiteral = 25,
        HexadecimalNationalLiteral = 26,
        DBCSLiteral = 27,
        LevelNumber = 28,
        IntegerLiteral = 29,
        DecimalLiteral = 30,
        FloatingPointLiteral = 31,
        PictureCharacterString = 32,
        CommentEntry = 33,
        ExecStatementText = 34,
        SectionParagraphName = 35,
        IntrinsicFunctionName = 36,
        ExecTranslatorName = 37,
        PartialCobolWord = 38,
        UserDefinedWord = 39,
        ASTERISK_CBL = 40,
        ASTERISK_CONTROL = 41,
        BASIS = 42,
        CBL = 43,
        COPY = 44,
        DELETE_CD = 45,
        EJECT = 46,
        ENTER = 47,
        EXEC_SQL_INCLUDE = 48,
        INSERT = 49,
        PROCESS = 50,
        READY = 51,
        RESET = 52,
        REPLACE = 53,
        SERVICE_CD = 54,
        SKIP1 = 55,
        SKIP2 = 56,
        SKIP3 = 57,
        TITLE = 58,
        ACCEPT = 59,
        ADD = 60,
        ALTER = 61,
        APPLY = 62,
        CALL = 63,
        CANCEL = 64,
        CLOSE = 65,
        COMPUTE = 66,
        CONFIGURATION = 67,
        CONTINUE = 68,
        DATA = 69,
        DECLARATIVES = 70,
        DECLARE = 71,
        DELETE = 72,
        DISPLAY = 73,
        DIVIDE = 74,
        ELSE = 75,
        END = 76,
        END_ADD = 77,
        END_CALL = 78,
        END_COMPUTE = 79,
        END_DECLARE = 80,
        END_DELETE = 81,
        END_DIVIDE = 82,
        END_EVALUATE = 83,
        END_EXEC = 84,
        END_IF = 85,
        END_INVOKE = 86,
        END_MULTIPLY = 87,
        END_PERFORM = 88,
        END_READ = 89,
        END_RETURN = 90,
        END_REWRITE = 91,
        END_SEARCH = 92,
        END_START = 93,
        END_STRING = 94,
        END_SUBTRACT = 95,
        END_UNSTRING = 96,
        END_WRITE = 97,
        END_XML = 98,
        ENTRY = 99,
        ENVIRONMENT = 100,
        EVALUATE = 101,
        EXEC = 102,
        EXECUTE = 103,
        EXIT = 104,
        FD = 105,
        FILE = 106,
        FILE_CONTROL = 107,
        GO = 108,
        GOBACK = 109,
        I_O_CONTROL = 110,
        ID = 111,
        IDENTIFICATION = 112,
        IF = 113,
        INITIALIZE = 114,
        INPUT_OUTPUT = 115,
        INSPECT = 116,
        INVOKE = 117,
        LINKAGE = 118,
        LOCAL_STORAGE = 119,
        MERGE = 120,
        MOVE = 121,
        MULTIPLE = 122,
        MULTIPLY = 123,
        NEXT = 124,
        OBJECT_COMPUTER = 125,
        OPEN = 126,
        PERFORM = 127,
        PROCEDURE = 128,
        READ = 129,
        RELEASE = 130,
        REPOSITORY = 131,
        RERUN = 132,
        RETURN = 133,
        REWRITE = 134,
        SAME = 135,
        SD = 136,
        SEARCH = 137,
        SELECT = 138,
        SERVICE = 139,
        SET = 140,
        SORT = 141,
        SOURCE_COMPUTER = 142,
        SPECIAL_NAMES = 143,
        START = 144,
        STOP = 145,
        STRING = 146,
        SUBTRACT = 147,
        UNSTRING = 148,
        USE = 149,
        WHEN = 150,
        WORKING_STORAGE = 151,
        WRITE = 152,
        XML = 153,
        ADDRESS = 154,
        DEBUG_CONTENTS = 155,
        DEBUG_ITEM = 156,
        DEBUG_LINE = 157,
        DEBUG_NAME = 158,
        DEBUG_SUB_1 = 159,
        DEBUG_SUB_2 = 160,
        DEBUG_SUB_3 = 161,
        JNIENVPTR = 162,
        LENGTH = 163,
        LINAGE_COUNTER = 164,
        RETURN_CODE = 165,
        SHIFT_IN = 166,
        SHIFT_OUT = 167,
        SORT_CONTROL = 168,
        SORT_CORE_SIZE = 169,
        SORT_FILE_SIZE = 170,
        SORT_MESSAGE = 171,
        SORT_MODE_SIZE = 172,
        SORT_RETURN = 173,
        TALLY = 174,
        WHEN_COMPILED = 175,
        XML_CODE = 176,
        XML_EVENT = 177,
        XML_INFORMATION = 178,
        XML_NAMESPACE = 179,
        XML_NAMESPACE_PREFIX = 180,
        XML_NNAMESPACE = 181,
        XML_NNAMESPACE_PREFIX = 182,
        XML_NTEXT = 183,
        XML_TEXT = 184,
        HIGH_VALUE = 185,
        HIGH_VALUES = 186,
        LOW_VALUE = 187,
        LOW_VALUES = 188,
        NULL = 189,
        NULLS = 190,
        QUOTE = 191,
        QUOTES = 192,
        SPACE = 193,
        SPACES = 194,
        ZERO = 195,
        ZEROES = 196,
        ZEROS = 197,
        SymbolicCharacter = 198,
        SELF = 199,
        SUPER = 200,
        ACCESS = 201,
        ADVANCING = 202,
        AFTER = 203,
        ALL = 204,
        ALPHABET = 205,
        ALPHABETIC = 206,
        ALPHABETIC_LOWER = 207,
        ALPHABETIC_UPPER = 208,
        ALPHANUMERIC = 209,
        ALPHANUMERIC_EDITED = 210,
        ALSO = 211,
        ALTERNATE = 212,
        AND = 213,
        ANY = 214,
        ARE = 215,
        AREA = 216,
        AREAS = 217,
        ASCENDING = 218,
        ASSIGN = 219,
        AT = 220,
        ATTRIBUTE = 221,
        ATTRIBUTES = 222,
        AUTHOR = 223,
        BEFORE = 224,
        BEGINNING = 225,
        BINARY = 226,
        BLANK = 227,
        BLOCK = 228,
        BOTTOM = 229,
        BY = 230,
        CHARACTER = 231,
        CHARACTERS = 232,
        CLASS = 233,
        CLASS_ID = 234,
        COBOL = 235,
        CODE = 236,
        CODE_SET = 237,
        COLLATING = 238,
        COM_REG = 239,
        COMMA = 240,
        COMMON = 241,
        COMP = 242,
        COMP_1 = 243,
        COMP_2 = 244,
        COMP_3 = 245,
        COMP_4 = 246,
        COMP_5 = 247,
        COMPUTATIONAL = 248,
        COMPUTATIONAL_1 = 249,
        COMPUTATIONAL_2 = 250,
        COMPUTATIONAL_3 = 251,
        COMPUTATIONAL_4 = 252,
        COMPUTATIONAL_5 = 253,
        CONTAINS = 254,
        CONTENT = 255,
        CONVERTING = 256,
        CORR = 257,
        CORRESPONDING = 258,
        COUNT = 259,
        CURRENCY = 260,
        DATE = 261,
        DATE_COMPILED = 262,
        DATE_WRITTEN = 263,
        DAY = 264,
        DAY_OF_WEEK = 265,
        DBCS = 266,
        DEBUGGING = 267,
        DECIMAL_POINT = 268,
        DELIMITED = 269,
        DELIMITER = 270,
        DEPENDING = 271,
        DESCENDING = 272,
        DISPLAY_1 = 273,
        DIVISION = 274,
        DOWN = 275,
        DUPLICATES = 276,
        DYNAMIC = 277,
        EGCS = 278,
        ELEMENT = 279,
        END_OF_PAGE = 280,
        ENDING = 281,
        EOP = 282,
        EQUAL = 283,
        ERROR = 284,
        EVERY = 285,
        EXCEPTION = 286,
        EXTEND = 287,
        EXTERNAL = 288,
        FACTORY = 289,
        FALSE = 290,
        FILLER = 291,
        FIRST = 292,
        FOOTING = 293,
        FOR = 294,
        FROM = 295,
        FUNCTION = 296,
        FUNCTION_POINTER = 297,
        GENERATE = 298,
        GIVING = 299,
        GLOBAL = 300,
        GREATER = 301,
        GROUP_USAGE = 302,
        I_O = 303,
        IN = 304,
        INDEX = 305,
        INDEXED = 306,
        INHERITS = 307,
        INITIAL = 308,
        INPUT = 309,
        INSTALLATION = 310,
        INTO = 311,
        INVALID = 312,
        IS = 313,
        JUST = 314,
        JUSTIFIED = 315,
        KANJI = 316,
        KEY = 317,
        LABEL = 318,
        LEADING = 319,
        LEFT = 320,
        LESS = 321,
        LINAGE = 322,
        LINE = 323,
        LINES = 324,
        LOCK = 325,
        MEMORY = 326,
        METHOD = 327,
        METHOD_ID = 328,
        MODE = 329,
        MODULES = 330,
        MORE_LABELS = 331,
        NAME = 332,
        NAMESPACE = 333,
        NAMESPACE_PREFIX = 334,
        NATIONAL = 335,
        NATIONAL_EDITED = 336,
        NATIVE = 337,
        NEGATIVE = 338,
        NEW = 339,
        NO = 340,
        NONNUMERIC = 341,
        NOT = 342,
        NUMERIC = 343,
        NUMERIC_EDITED = 344,
        OBJECT = 345,
        OCCURS = 346,
        OF = 347,
        OFF = 348,
        OMITTED = 349,
        ON = 350,
        OPTIONAL = 351,
        OR = 352,
        ORDER = 353,
        ORGANIZATION = 354,
        OTHER = 355,
        OUTPUT = 356,
        OVERFLOW = 357,
        OVERRIDE = 358,
        PACKED_DECIMAL = 359,
        PADDING = 360,
        PAGE = 361,
        PARSE = 362,
        PASSWORD = 363,
        PIC = 364,
        PICTURE = 365,
        POINTER = 366,
        POSITION = 367,
        POSITIVE = 368,
        PROCEDURE_POINTER = 369,
        PROCEDURES = 370,
        PROCEED = 371,
        PROCESSING = 372,
        PROGRAM = 373,
        PROGRAM_ID = 374,
        RANDOM = 375,
        RECORD = 376,
        RECORDING = 377,
        RECORDS = 378,
        RECURSIVE = 379,
        REDEFINES = 380,
        REEL = 381,
        REFERENCE = 382,
        REFERENCES = 383,
        RELATIVE = 384,
        RELOAD = 385,
        REMAINDER = 386,
        REMOVAL = 387,
        RENAMES = 388,
        REPLACING = 389,
        RESERVE = 390,
        RETURNING = 391,
        REVERSED = 392,
        REWIND = 393,
        RIGHT = 394,
        ROUNDED = 395,
        RUN = 396,
        SECTION = 397,
        SECURITY = 398,
        SEGMENT_LIMIT = 399,
        SENTENCE = 400,
        SEPARATE = 401,
        SEQUENCE = 402,
        SEQUENTIAL = 403,
        SIGN = 404,
        SIZE = 405,
        SORT_MERGE = 406,
        SQL = 407,
        SQLIMS = 408,
        STANDARD = 409,
        STANDARD_1 = 410,
        STANDARD_2 = 411,
        STATUS = 412,
        SUPPRESS = 413,
        SYMBOL = 414,
        SYMBOLIC = 415,
        SYNC = 416,
        SYNCHRONIZED = 417,
        TALLYING = 418,
        TAPE = 419,
        TEST = 420,
        THAN = 421,
        THEN = 422,
        THROUGH = 423,
        THRU = 424,
        TIME = 425,
        TIMES = 426,
        TO = 427,
        TOP = 428,
        TRACE = 429,
        TRAILING = 430,
        TRUE = 431,
        TYPE = 432,
        UNBOUNDED = 433,
        UNIT = 434,
        UNTIL = 435,
        UP = 436,
        UPON = 437,
        USAGE = 438,
        USING = 439,
        VALIDATING = 440,
        VALUE = 441,
        VALUES = 442,
        VARYING = 443,
        WITH = 444,
        WORDS = 445,
        WRITE_ONLY = 446,
        XML_DECLARATION = 447,
        XML_SCHEMA = 448,
        YYYYDDD = 449,
        YYYYMMDD = 450,
        TYPEDEF = 451,
        STRONG = 452,
        UNSAFE = 453,
        PUBLIC = 454,
        PRIVATE = 455,
        IN_OUT = 456,
        STRICT = 457,

        //Last Keyword is referend in TokenUtils() with keywordEnd

        //Operators - TypeCobol
        QuestionMark = 458,
        // Group of tokens produced by the preprocessor
        // - compiler directives
        CompilerDirective = 459,
        CopyImportDirective = 460,
        ReplaceDirective = 461,
        // - internal token groups -> used by the preprocessor only
        ContinuationTokenGroup = 462,

    }

    public static class TokenConst {
        private static readonly TokenType[] TypeCobolTokenType =
        {
            TokenType.DECLARE, TokenType.END_DECLARE, TokenType.PUBLIC, TokenType.PRIVATE, TokenType.IN_OUT,
            TokenType.UNSAFE, TokenType.STRICT, TokenType.QuestionMark
        };

        private static readonly TokenType[] Cobol2002TokenType = {TokenType.STRONG, TokenType.TYPEDEF};

        public static CobolLanguageLevel GetCobolLanguageLevel(TokenType tokenType) {
            if (TypeCobolTokenType.Contains(tokenType))
            {
                return CobolLanguageLevel.TypeCobol;
            }
            if (Cobol2002TokenType.Contains(tokenType))
            {
                return CobolLanguageLevel.Cobol2002;
            }
            return CobolLanguageLevel.Cobol85;
        }
    }
}