* Format 1
DIVIDE a INTO b
DIVIDE a INTO b c
DIVIDE 42 INTO b ROUNDED c d ROUNDED
* Format 2
DIVIDE a INTO b GIVING c
DIVIDE 42 INTO b GIVING c d
DIVIDE a INTO b GIVING c ROUNDED d e ROUNDED
* Format 3
DIVIDE 42 BY b GIVING c
DIVIDE a BY b GIVING c d
DIVIDE a BY 42 GIVING c ROUNDED d e ROUNDED
* Format 4
DIVIDE a INTO 42 GIVING c REMAINDER d
DIVIDE 42 INTO b GIVING c ROUNDED REMAINDER d
* Format 5
DIVIDE 42 BY 42 GIVING c REMAINDER d
DIVIDE a BY b GIVING c ROUNDED REMAINDER d

* Invalid
DIVIDE.
DIVIDE var1 FROM var2.
DIVIDE var1 WITH var2.