MULTIPLY a BY b
MULTIPLY a BY b ROUNDED
MULTIPLY a BY b c
MULTIPLY a BY b ROUNDED c
MULTIPLY 42 BY b
MULTIPLY 42 BY b ROUNDED
MULTIPLY 42 BY b c
MULTIPLY 42 BY b GIVING c
MULTIPLY 42 BY 101010 GIVING c d ROUNDED
* Invalid
MULTIPLY.
MULTIPLY var1 INTO var2.
MULTIPLY var1 WITH var2.