# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test one configuration

on:
  workflow_call:
    inputs:
      build-configuration:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Build
      run: dotnet build --no-restore --configuration ${{ inputs.build-configuration }}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${{ inputs.build-configuration }}
